### ISSUE TITLE
The read operation timed out

### ISSUE THREAD

**Issue by nirs** [nirs/oci#43]
I'm not sure what ere the network conditions when this happened, the network in this location
is sometimes flay.

Just before the failure, I trried to access https://jenkins.ovirt.org/queue/item/19938/
and it failed with 404. 

```
$ ./ovirt-ci system-tests 102462
[ 1/8 ] Getting build info for change 102462
[ 2/8 ] Starting build-artifacts job
        project: vdsm   branch: master   patchset: 1
[ 3/8 ] Waiting until job is executed
        queue: https://jenkins.ovirt.org/queue/item/19931/
[ 4/8 ] Waiting until job is completed
        job: http://jenkins.ovirt.org/job/standard-manual-runner/584/
[ 5/8 ] Starting oVirt system tests job
        suite: basic   repo: http://jenkins.ovirt.org/job/standard-manual-runner/584/
[ 6/8 ] Waiting until job is executed
        queue: https://jenkins.ovirt.org/queue/item/19938/
Traceback (most recent call last):
  File "./ovirt-ci", line 3, in <module>
    main.run()
  File "/home/nsoffer/src/oci/oci/main.py", line 65, in run
    args.command(args)
  File "/home/nsoffer/src/oci/oci/main.py", line 154, in system_tests
    job_url = ja.wait_for_queue(queue_url)
  File "/home/nsoffer/src/oci/oci/network.py", line 73, in wrapper
    return func(*a, **kw)
  File "/home/nsoffer/src/oci/oci/jenkins.py", line 162, in wait_for_queue
    timeout=timeout)
  File "/home/nsoffer/src/oci/oci/jenkins.py", line 210, in _wait_for
    res = con.getresponse()
  File "/usr/lib64/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib64/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib64/python2.7/ssl.py", line 772, in recv
    return self.read(buflen)
  File "/usr/lib64/python2.7/ssl.py", line 659, in read
    v = self._sslobj.read(len)
ssl.SSLError: ('The read operation timed out',)
```

**Comment by vjuranek** [comment]
IMHO it's very likely issue on Jenkins site (Jenkins being very slow) - I just hit the same issue and all other network connections didn't failed. Maybe we should increase default timeout? Or make configurable by the user via `ovirt-ci.conf`?
